#!/usr/bin/env php
<?php

use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;
use Illuminate\Container\Container;

use Rowles\Console\Commands\GenerateThumbnailCommand;
use Rowles\Console\Commands\GeneratePreviewCommand;
use Rowles\Console\Commands\TranscodeVideoCommand;

require_once __DIR__.'/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$version = "7.0";

$container = new Container;
$dispatcher = new Dispatcher;

$app = new Application($container, $dispatcher, $version);

$app->add(new GenerateThumbnailCommand);
$app->add(new GeneratePreviewCommand);
$app->add(new TranscodeVideoCommand);

$app->run();